// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq8O5ZoQo_OttzxXVVAvQ_CFbDt0nBoIg',
    appId: '1:908575927764:web:7f7baf4542ebe114cc3a41',
    messagingSenderId: '908575927764',
    projectId: 'hellojex-2c22d',
    authDomain: 'hellojex-2c22d.firebaseapp.com',
    storageBucket: 'hellojex-2c22d.firebasestorage.app',
    measurementId: 'G-C2KKPNF15N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiWFkSw4f1F47yiCzkkqO-7WaHnF5Nuto',
    appId: '1:908575927764:android:fa8bcec0550966e5cc3a41',
    messagingSenderId: '908575927764',
    projectId: 'hellojex-2c22d',
    storageBucket: 'hellojex-2c22d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOy3zys6uxCBbFPAXPQrUubTOQKCMDXFc',
    appId: '1:908575927764:ios:3aa2fc3e89125ddfcc3a41',
    messagingSenderId: '908575927764',
    projectId: 'hellojex-2c22d',
    storageBucket: 'hellojex-2c22d.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOy3zys6uxCBbFPAXPQrUubTOQKCMDXFc',
    appId: '1:908575927764:ios:3aa2fc3e89125ddfcc3a41',
    messagingSenderId: '908575927764',
    projectId: 'hellojex-2c22d',
    storageBucket: 'hellojex-2c22d.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq8O5ZoQo_OttzxXVVAvQ_CFbDt0nBoIg',
    appId: '1:908575927764:web:dcfaf4c67dea4368cc3a41',
    messagingSenderId: '908575927764',
    projectId: 'hellojex-2c22d',
    authDomain: 'hellojex-2c22d.firebaseapp.com',
    storageBucket: 'hellojex-2c22d.firebasestorage.app',
    measurementId: 'G-7TX01XXK0Y',
  );
}
